apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 1
  template:
    metadata:
      labels:
        app: node-api
    spec:
      serviceAccountName: node-apis
      containers:
        - name: node-api
          image: ilthi96/node-api:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  type: LoadBalancer
  selector:
    app: node-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-apis
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-apis
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-apis
  namespace: default
subjects:
  - kind: ServiceAccount
    name: node-apis
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-apis
